# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4447cf07908b41409bcc50d818021185387ddfbca6cad3597fbe4af81396ba448335ec1b3c80c8e0ad14424fc1e3533570ab91c09632a821ef81755154a1455e

test:
  secret_key_base: dba308e112bef8a60cfa420ca8e911e2842dc2b7099eea87bd54e2a634576c010b66903d27bc6768b4adefb443b8b4fd059cf29ae844b09490d7a3a0feee1412

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
